### ISSUE TITLE
module and packages

### ISSUE THREAD

**Issue by bconn98** [bconn98/DrugRecord#1]
https://forum.golangbridge.org/t/modules-and-packages/19264/4

**Comment by hollowaykeanho** [comment]
If I'm based on your https://github.com/bconn98/DrugRecord/tree/modules branch, on root level, there is still a missing `go.mod` file. Can you place the module in it?

**Comment by bconn98** [comment]
Odd, it hasn't added it. One moment

**Comment by bconn98** [comment]
Fixed

**Comment by hollowaykeanho** [comment]
meaning?

**Comment by bconn98** [comment]
It can now be found on github

**Comment by hollowaykeanho** [comment]
Can it import the internal package?

**Comment by bconn98** [comment]
I was unsure what I needed to do for internal packages. I found a lot of conflicting material

**Comment by hollowaykeanho** [comment]
Paste output.

**Comment by bconn98** [comment]
# github.com/bconn98/DrugRecord/mainUtils
mainUtils\excelWriter.go:30:22: file.MergeCell(acName, "A7", "C7") used as value
mainUtils\excelWriter.go:31:22: file.MergeCell(acName, "D7", "F7") used as value
mainUtils\excelWriter.go:32:22: file.MergeCell(acName, "A9", "F9") used as value
mainUtils\excelWriter.go:37:29: file.SetCellFormula(acName, "G" + strconv.Itoa(i), "=G" + strconv.Itoa(i - 1) + " + C" + strconv.Itoa(i) + "- F" + strconv.Itoa(i)) used as value
mainUtils\excelWriter.go:45:33: undefined: excelize.StreamWriter
mainUtils\excelWriter.go:48:22: undefined: excelize.Cell
mainUtils\excelWriter.go:51:3: undefined: excelize.Cell
mainUtils\excelWriter.go:203:33: undefined: excelize.StreamWriter
mainUtils\excelWriter.go:231:35: undefined: excelize.StreamWriter
mainUtils\excelWriter.go:255:33: undefined: excelize.StreamWriter
mainUtils\excelWriter.go:51:3: too many errors

**Comment by bconn98** [comment]
If I remove the module part: "webServer.go:15:2: package mainUtils is not in GOROOT (C:\Go\src\mainUtils)"

**Comment by hollowaykeanho** [comment]
No you don't need to remove `mainUtils` because it's part of child packages. 

Can you x-check github.com/360EntSecGroup-Skylar/excelize version 1.4.1 is the version you're using?

The error messages imply that excelize has a lot of missing fucntions.

**Comment by bconn98** [comment]
It works without modules (master branch) using the most recent release

**Comment by bconn98** [comment]
Shit, you're right. 1.4 is old and doesn't have the new stuff I need.

**Comment by hollowaykeanho** [comment]
> It works without modules (master branch) using the most recent release
This is where it imports using the conventional GOPATH method. In Module, you have to be very specific about the dependency version you're using. Currently, module is complaining that dependency does not facilitates those functions.

So keywords you can use to cross check is:

`StreamWriter` and `MergeCell`. 

Try get the version you want.

**Comment by bconn98** [comment]
A:\Documents\JetBrains\GolandProjects\DrugRecord\go.mod:6: require github.com/360EntSecGroup-Skylar/excelize: version "v2.2.0" invalid: module contains a go.mod file, so major version must be compatible: should be v0 or v1, not v2

**Comment by hollowaykeanho** [comment]
make sure you require `github.com/360EntSecGroup-Skylar/excelize/v2`. Notice the `v2` pathing behinds it.

**Comment by bconn98** [comment]
When I ran it that time it brought the old one back.
	github.com/360EntSecGroup-Skylar/excelize v1.4.1
	github.com/360EntSecGroup-Skylar/excelize/v2 v2.2.0

**Comment by bconn98** [comment]
Was there something I had to add to my import of it? Feel like I saw that somewhere earlier but I forget what it was.

**Comment by hollowaykeanho** [comment]
> Was there something I had to add to my import of it? 
Nahh. 

What you need to now is to remove the `go.sum` first. Then tidy up the `go.mod` by removing the `v1.4.1`. Then try build/test the binary.

**Comment by bconn98** [comment]
Same thing

**Comment by hollowaykeanho** [comment]
Woah, let me review the excelWriter source codes. One of the source code is still importing `v1.4.1` package.

**Comment by bconn98** [comment]
Got it, I had to update the import statement. Thank you for all your help.

**Comment by bconn98** [comment]
In mainUtils/excelWriter.go
`import (
	"strconv"
	"strings"
	"time"

	excelize "github.com/360EntSecGroup-Skylar/excelize/v2"
)`

**Comment by hollowaykeanho** [comment]
haha.. well everything works as expected?

**Comment by bconn98** [comment]
Yes sir

**Comment by hollowaykeanho** [comment]
Okay, let's close this github ticket.. I will reply in the forum as a single summary.

**Comment by hollowaykeanho** [comment]
Done. Please "mark as solved" for my conclusion so that others can search and self-learn too. =)
